[package]
name = "thirtyfour_webdriver_console_second"
version = "0.1.0"
edition = "2021"

[dependencies]
thirtyfour = "0.32.0"
tokio = { version = "1.38.1", features = ["full"] }
env_logger = "0.11.3"
log = "0.4.22"
